spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

  info:
    title: User Service API
    description: API for managing users
    version: 1.0.0


